import React from "react"
import classes from './style.module.css';
import { Button, Grid, Typography } from "@material-ui/core";
import Head from "next/head";
import Emoji from "../Emoji/Emoji";

const Redirect: React.FC = () => {

    return (
        <>
            <div className={classes.container}>
                <Head>
                    <title>Four in line App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Grid container
                    direction="column"
                    justify="center"
                    alignItems="center"
                    spacing={8}
                >
                    <Grid item xs={12} >
                        <Typography variant="h3" className={classes.title}>
                            <span className={classes.fontStyle}> Welcome to four in line app! </span>
                            <Emoji label="happyFace" symbol="😁" />
                        </Typography>
                    </Grid>
                </Grid>
                <Grid container
                    direction="column"
                    justify="center"
                    alignItems="center"
                    spacing={5}
                >
                    <Grid item xs={12} spacing={3}>
                        <Typography variant="h4">
                            <span className={classes.fontStyle}>Please choose your color
                            <Emoji label="happyFace" symbol="😎" />
                            </span>
                        </Typography>
                    </Grid>
                </Grid>
                <Grid container
                    direction="row"
                    justify="center"
                    alignItems="center"
                    spacing={5}
                >
                    <Grid item xs={3} spacing={3}>
                        <Button variant="contained" color="secondary" onClick={() => window.location.href = "/red"} value="red">
                            <Typography variant="h6"><span className={classes.fontStyle}>Red player</span>
                            </Typography>
                        </Button>

                    </Grid>
                    <Grid item xs={3}>
                        <Button variant="contained" color="secondary" onClick={() => window.location.href = "/yellow"} value="yellow">
                            <Typography variant="h6"> <span className={classes.fontStyle}> Yellow Player </span>
                            </Typography>
                        </Button>
                    </Grid>
                </Grid>

            </div>

        </>

    )
}
export default Redirect;