import Head from 'next/head'
import React, { useState } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {
 
  return (
    <>
    <Head>
    <title>Four in lines App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
         <h3 className={styles.title}>
          Welcome to Four in line app!
        </h3>

    </>
  )
}

